name: epub_reader
description: A multi-language EPUB reader
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  epubx: ^4.0.0
  path_provider: ^2.1.1
  flutter_localizations:
    sdk: flutter
  http: ^1.1.0
  flutter_html: ^3.0.0-beta.2
  webview_flutter: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/books/